version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_development
    ports:
      - "5432:5432"
    networks:
      - sql_injection
  myapp:
    build : .
    container_name: sql_injection
    ports:
      - "8080:8080"
    networks:
      - sql_injection
    links:
      - postgres
    depends_on:
      - postgres
networks:
  sql_injection:
    driver: bridge